[Master]
source                    = notmuch://~/.mail
outgoing                  = /usr/bin/msmtp
default                   = Inbox 
from                      = Amir Habirov <amirhabirov@disroot.org>
maildir-store             = ~/.mail
query-map                 = ~/.config/aerc/Master.qmap
folders-sort              = Unread,Today,Week,All,Inbox,Archive,Drafts,Sent,Trash,Junk
pgp-auto-sign             = true
pgp-attach-key            = true
pgp-self-encrypt          = true
pg-error-level            = error
pgp-key-id                = 727B27274B05785D
pgp-opportunistic-encrypt = true
