[amirhabirov@disroot.org]
copy-to                   = Sent
copy-to-replied           = true
default                   = Inbox
folders                   = Inbox,Archive,Sent,Drafts,Trash,Spam
folders-sort              = Inbox,Archive,Sent,Drafts,Trash,Spam
from                      = Amir Habirov <amirhabirov@disroot.org>
use-envelope-from         = true
outgoing                  = /usr/bin/msmtp
pgp-auto-sign             = true
pgp-attach-key            = true
pgp-self-encrypt          = true
pgp-error-level           = error
pgp-opportunistic-encrypt = true
check-mail-timeout        = 30s
source                    = notmuch://~/.mail
query-map                 = ~/.config/aerc/amirhabirov@disroot.org.qmap
maildir-store             = ~/.mail
restrict-delete           = true
