[general]
pgp-provider          = gpg

[ui]
column-separator      = " | "
sidebar-width         = 9
new-message-bell      = false
styleset-name         = buistvokrasok

[viewer]
pager                 = vim -Rc "set ls=0 nonu nornu noma" -
header-layout         = From,To,Cc,Bcc,Date,Subject

[compose]
editor                = vim -c "set cc=65"
header-layout         = To,From,Subject
empty-subject-warning = true
format-flowed         = true

[filters]
text/plain            = fmt -w 65

