?        = :help keys<Enter>
<space>t = :term<Enter>
<space>r = :reload<Enter>
<C-n>    = :next-tab<Enter>
<C-p>    = :prev-tab<Enter>

[messages]
<Enter> = :view<Enter>
q       = :quit<Enter>
j       = :next<Enter>:align center<Enter>
k       = :prev<Enter>:align center<Enter>
<C-j>   = :next-folder<Enter>
<C-k>   = :prev-folder<Enter>
n       = :next-result<Enter>:align center<Enter>
N       = :prev-result<Enter>:align center<Enter>
g       = :select 0<Enter>
G       = :select -1<Enter>
v       = :unmark -a<Enter>:mark -t<Enter>
V       = :unmark -a<Enter>:mark -v<Enter>
i       = :move Inbox<Enter>
a       = :move Archive<Enter>
t       = :move Trash<Enter>
s       = :move Spam<Enter>
c       = :compose<Enter>
b       = :bounce<space>
rr      = :reply -a<Enter>
rq      = :reply -aq<Enter>
Rr      = :reply<Enter>
Rq      = :reply -q<Enter>
!       = :term<space>
|       = :pipe<space>
/       = :search<space>
\       = :filter<space>
<Esc>   = :clear<Enter>:unmark -a<Enter>

[messages:folder=Drafts]
<Enter> = :recall<Enter>

[view]
q     = :close<Enter>
o     = :open-link<space><Tab>
f     = :forward<Enter>
rr    = :reply -a<Enter>
rq    = :reply -aq<Enter>
Rr    = :reply<Enter>
Rq    = :reply -q<Enter>
<C-j> = :next<Enter>
<C-k> = :prev<Enter>
|     = :pipe<space>

[compose]
# Keybindings used when the embedded terminal is not selected in the compose view
$noinherit = true
$ex        = <A-x>
<C-k>      = :prev-field<Enter>
<C-j>      = :next-field<Enter>
<C-p>      = :prev-tab<Enter>
<C-n>      = :next-tab<Enter>
<space>t   = :term<Enter>

[compose::editor]
# Keybindings used when the embedded terminal is selected in the compose view
$noinherit = true
$ex        = <A-x>
<C-k>      = :prev-field<Enter>
<C-j>      = :next-field<Enter>
<C-p>      = :prev-tab<Enter>
<C-n>      = :next-tab<Enter>
<space>t   = :term<Enter>

[compose::review]
# Keybindings used when reviewing a message to be sent
# Inline comments are used as descriptions on the review screen
y = :send<Enter>     # Send
n = :abort<Enter>    # Abort (discard message, no confirmation)
s = :sign<Enter>     # Toggle signing
x = :encrypt<Enter>  # Toggle encryption to all recipients
v = :preview<Enter>  # Preview message
p = :postpone<Enter> # Postpone
e = :edit<Enter>     # Edit (body and headers)
a = :attach<space>   # Add attachment
d = :detach<space>   # Remove attachment

[terminal]
$noinherit = true
$ex        = <A-x>
<space>t   = :term<Enter>
<C-n>      = :next-tab<Enter>
<C-p>      = :prev-tab<Enter>
