set -g base-index 1
set -g status-right ""
set -g status-bg "#d3d3d3"
set -g status-fg "#333333"
set -g mode-keys vi
set -g set-clipboard on

bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip"
